{
 "title": "Syslog Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Syslog Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\"}[1h])"
    }
   ]
  },
  {
   "title": "Syslog Count Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate({job=\"syslog\"}[1m])"
    }
   ]
  },
  {
   "title": "Log Panel",
   "type": "logs",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"}"
    }
   ]
  },
  {
   "title": "Syslog Entries with Filenames",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{job=\"syslog\"} |= \"filename\""
    }
   ]
  }
 ]
}